# config.yaml
google_drive_folder_id: "1aHrMTr3_nrLiN0sJ6_RTjr0NM230Pi3A"  # Replace with your folder ID
service_account_file: "/home/riku/secure-keys/api-project-970767241608-5f275b1e55da.json" # service account
scopes:
  - "https://www.googleapis.com/auth/drive.readonly"
embedding_model: "all-MiniLM-L6-v2"
mistral_model_path: "/home/riku/models/mistral-7b-v0.1.Q4_K_M.gguf"
index_path: "faiss_index/index.faiss"
chunk_size: 500
overlap: 50
top_k: 5
log_level: "INFO"
log_file: "rag_pipeline.log"
interactive: True # Default for interactive
